
app_id: "**********************************************************"
app_secret: "******************************************************"
redirect: "********************************************************"
scopes:
  - user.read
  - mailboxsettings.read
  - calendars.readwrite
authority: "*******************************************************"
